// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoTrader.Migrations
{
    [DbContext(typeof(AutoTraderDBContext))]
    [Migration("20220102213334_AddLogBookTable")]
    partial class AddLogBookTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("AutoTrader.Data.AssetPairEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Accuracy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuotingAssetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("assetPairEntities");
                });

            modelBuilder.Entity("AutoTrader.Data.LogBookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetPairId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("logBookEntry")
                        .HasColumnType("TEXT");

                    b.Property<string>("reason")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("logBooks");
                });

            modelBuilder.Entity("AutoTrader.Data.PriceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ask")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetPairId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Bid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("priceEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
