// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoTrader.Migrations
{
    [DbContext(typeof(AutoTraderDBContext))]
    partial class AutoTraderDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("AutoTrader.Data.AssetPairEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Accuracy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuotingAssetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("assetPairEntities");
                });

            modelBuilder.Entity("AutoTrader.Data.PriceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("Ask")
                        .HasColumnType("REAL");

                    b.Property<string>("AssetPairId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Bid")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("priceEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
